### ISSUE TITLE
Error installing libecl with python 3.7

### ISSUE THREAD

**Issue by Alejobep** [equinor/libecl#657]
I get the following errors after I type `make`:

```
.../libecl/lib/ecl/smspec_node.cpp: In member function ‘void ecl::smspec_node::set_gen_keys(const char*)’:
.../libecl/lib/ecl/smspec_node.cpp:601: error: template argument for ‘template<class _Tp, class _Tp_Deleter> class std::unique_ptr’ uses local type ‘ecl::smspec_node::set_gen_keys(const char*)::deleter’
compilation terminated due to -Wfatal-errors.
make[2]: *** [lib/CMakeFiles/ecl.dir/ecl/smspec_node.cpp.o] Error 1
make[1]: *** [lib/CMakeFiles/ecl.dir/all] Error 2
make: *** [all] Error 2

```

I sthere something I need to edit from `build`

**Comment by markusdregi** [comment]
Hi @Alejobep.

Could you provide us with a little more details? Also, note that none of the developers have tested libecl with Python 3.7 yet. I don't expect any problems as it works fine with 3.6, but still good to know...

**Comment by markusdregi** [comment]
Built libecl successfully on my machine with Python 3.7. Closed due to lack of information.
